import Header from '@/components/Header';
import Slider from '@/components/Slider';
import Head from 'next/head';
import { useEffect, useRef, useState } from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Music Agency</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='uppercase text-[#010101]'>
        <Header />
        <Slider />
      </div>
    </>
  );
}
