import About from '@/components/About';
import Navbar from '@/components/Navbar';
import Slider from '@/components/Slider';
import Brands from '@/components/Brands';
import Footer from '@/components/Footer';
import Head from 'next/head';
import { useEffect, useRef, useState } from 'react';
import { Office } from '@/components/Office';

export default function Home() {
  return (
    <>
      <Head>
        <title>Music Agency</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='uppercase text-[#010101]'>
        <Navbar />
        <Slider />
        <About />
        <Brands />
        <Office />
        <Footer />
      </div>
    </>
  );
}
